version: '3.7'

services:
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -c "python app.py"
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    links:
      - redis
    env_file:
      - envs/dev.env

volumes:
    redis_data:
    pgadmin: